spring.application.name=mail-service
server.port=8082

# --- RabbitMQ ---
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_DEFAULT_USER:guest}
spring.rabbitmq.password=${RABBITMQ_DEFAULT_PASS:guest}

# Configuração de E-mail
spring.mail.host=${MAILTRAP_HOST:localhost}
spring.mail.port=${MAILTRAP_PORT:1025}
spring.mail.username=${MAILTRAP_USER:test}
spring.mail.password=${MAILTRAP_PASS:test}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# --- Actuator & Prometheus Monitoring ---
management.endpoints.web.exposure.include=health,info,prometheus
management.prometheus.metrics.export.enabled=true
management.endpoint.health.show-details=always

frontend.base-url=${FRONTEND_DASHBOARD_URL:http://localhost:3000}

spring.threads.virtual.enabled=true
logging.config=classpath:logback-shared.xml

initial.admin.email=${INITIAL_ADMIN_EMAIL:admin@petshop.local}

## --- Conexao com Banco (Docker ou local) ---
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:petshop_mail}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update